channels:
  - defaults
  - r
dependencies:
  - python=3
  - numpy
  - scipy
  - pandas
  - networkx
  - matplotlib
  - sympy
  - scikit-learn
  - pydot
  - seaborn
  - pygraphviz
  - rpy2
  - ipython
  - jupyter
  - notebook
  - simplegeneric
  - pip:
    - graphviz
